name: Build and Commit Shared Libraries

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:
    permissions:
      # Разрешить запуск workflow только участникам репозитория
      runs: write 
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: so
            compiler: g++
          - os: macos-latest
            extension: dylib
            compiler: g++
          - os: windows-latest
            extension: dll
            compiler: g++ 

    steps:
      - uses: actions/checkout@v3

      - name: Create libs directory
        run: mkdir libs
        working-directory: ./

      - name: Compile shared libraries
        run: |
          ${{ matrix.compiler }} -shared -fPIC -o libs/l1_1.${{ matrix.extension }} l1_1.cpp
          ${{ matrix.compiler }} -shared -fPIC -o libs/l1_2.${{ matrix.extension }} l1